export const FETCH_DATA_REQUEST = "FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS = "FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE = "FETCH_DATA_FAILURE";

export const FETCH_EPISODE_REQUEST = "FETCH_EPISODE_REQUEST";
export const FETCH_EPISODE_SUCCESS = "FETCH_EPISODE_SUCCESS";
export const FETCH_EPISODE_FAILURE = "FETCH_EPISODE_FAILURE";
